image: node

stages:
    - deps
    - test

before_script:
    - cd app

cache:
    paths:
        - app/node_modules/

Deps:
    stage: deps
    script:
        - npm install
    artifacts:
        paths:
            - app/node_modules/

Lint:
    stage: test
    before_script:
        - npm install --only=dev
    script:
        - curl https://install.meteor.com/ | sh
        - meteor npm run lint

Test:
    stage: test
    script:
        - curl https://install.meteor.com/ | sh
        - npm test
