export const structureOptions = [
  { value: 'Ministère Education', label: 'Ministère Éducation' },
  { value: 'Éducation', label: 'Éducation' },
  { value: 'Auvergne-Rhône-Alpes', label: 'Région académique Auvergne-Rhône-Alpes' },
  { value: 'Bourgogne-Franche-Comté', label: 'Région académique Bourgogne-Franche-Comté' },
  { value: 'Bretagne', label: 'Région académique Bretagne' },
  { value: 'Centre-Val de Loire', label: 'Région académique Centre-Val de Loire' },
  { value: 'Corse', label: 'Région académique de Corse' },
  { value: 'Grand Est', label: 'Région académique Grand Est' },
  { value: 'Guadeloupe', label: 'Région académique de la Guadeloupe' },
  { value: 'Guyane', label: 'Région académique de la Guyane' },
  { value: 'Hauts-de-France', label: 'Région académique Hauts-de-France' },
  { value: 'Île-de-France', label: 'Région académique Île-de-France' },
  { value: 'Martinique', label: 'Région académique de Martinique' },
  { value: 'Normandie', label: 'Région académique Normandie' },
  { value: 'Nouvelle-Aquitaine', label: 'Région académique Nouvelle-Aquitaine' },
  { value: 'Occitanie', label: 'Région académique Occitanie' },
  { value: 'Pays de la Loire', label: 'Région académique Pays de la Loire' },
  { value: "Provence-Alpes-Côte d'Azur", label: 'Région académique Provence-Alpes-Côte d&apos;Azur' },
  { value: 'La Réunion', label: 'Région académique de La Réunion' },
  { value: 'Collectivité', label: 'Collectivité' },
  { value: 'Autre', label: 'Autre' },
];

export const structures = structureOptions.map((opt) => opt.value);
